<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <Compile Remove="artifacts/**/*.cs" />
  </ItemGroup>
</Project>
