// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentWisePro.Web.Data;

#nullable disable

namespace RentWisePro.Web.Migrations
{
    [DbContext(typeof(RentWiseProDbContext))]
    [Migration("20260405120000_AddUserScopedProfilesAndSavedAnalyses")]
    partial class AddUserScopedProfilesAndSavedAnalyses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.InvestmentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AppraisalFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ClosingCostsPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CreditReportFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DownpaymentPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EscrowFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FloodInspectionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HOAEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HomeownersInsuranceAnnual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("InvestmentProfileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("LoanOriginationFeePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MiscellaneousFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyMaintenanceBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MonthlyUtilitiesCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MortgageInterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PMIRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PropertyManagementFeePct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PropertyTaxRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RealtorClosingFeePercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<decimal?>("TitleInsuranceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TitleSearchFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("VacancyRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("InvestmentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownpaymentPercentage = 20m,
                            HomeownersInsuranceAnnual = 0m,
                            InvestmentProfileName = "Default",
                            IsDefault = true,
                            MortgageInterestRate = 6.50m,
                            PMIRate = 0m,
                            PropertyTaxRate = 0m,
                            TermYears = 30,
                            UserId = "SYSTEM"
                        });
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.RentalListing", b =>
                {
                    b.Property<int>("RentalListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalListingId"));

                    b.Property<decimal?>("Bathrooms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EstimatedRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImgSrc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("IngestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TaxAssessedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("Zpid")
                        .HasColumnType("bigint");

                    b.HasKey("RentalListingId");

                    b.HasIndex("Zpid")
                        .IsUnique();

                    b.ToTable("RentalListings");
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.SavedPropertyProfile", b =>
                {
                    b.Property<int>("SavedPropertyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedPropertyProfileId"));

                    b.Property<decimal?>("ClosingCostOverride")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DownpaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvestmentProfileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyOtherExpensesOverride")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyRentOverride")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MortgageInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherUpfrontCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RenovationBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RentalListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SavedPropertyProfileId");

                    b.HasIndex("InvestmentProfileId");

                    b.HasIndex("RentalListingId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SavedAtUtc");

                    b.HasIndex("InvestmentProfileId", "RentalListingId")
                        .IsUnique();

                    b.ToTable("SavedPropertyProfiles");
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RentWisePro.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RentWisePro.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentWisePro.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RentWisePro.Web.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.SavedPropertyProfile", b =>
                {
                    b.HasOne("RentWisePro.Web.Domain.Entities.InvestmentProfile", "InvestmentProfile")
                        .WithMany("SavedPropertyProfiles")
                        .HasForeignKey("InvestmentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentWisePro.Web.Domain.Entities.RentalListing", "RentalListing")
                        .WithMany("SavedPropertyProfiles")
                        .HasForeignKey("RentalListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentProfile");

                    b.Navigation("RentalListing");
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.InvestmentProfile", b =>
                {
                    b.Navigation("SavedPropertyProfiles");
                });

            modelBuilder.Entity("RentWisePro.Web.Domain.Entities.RentalListing", b =>
                {
                    b.Navigation("SavedPropertyProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
